import Burpee_and_Jump_Exercise from '../assets/latihan/Burpee_and_Jump_Exercise.gif';
import Cobras_exercises from '../assets/latihan/Cobras_exercises.gif';
import Frog_press_excercise from '../assets/latihan/Frog_press_excercise.gif'
import Inchworm_workout_excercise from '../assets/latihan/Inchworm_workout_excercise.gif'
import Jumping_Jack_Excercise from '../assets/latihan/Jumping_Jack_Excercise.gif'
import Jumping_squats_excercise from '../assets/latihan/Jumping_squats_excercise.gif'
import Lunge_Excercise from '../assets/latihan/Lunge_Excercise.gif'
import Military_Push_Ups_Exercise from '../assets/latihan/Military_Push_Ups_Exercise.gif'
import Punches_Animation from '../assets/latihan/Punches_Animation.gif'
import Reverse_Crunches_Excercise from '../assets/latihan/Reverse_Crunches_Excercise.gif'
import Seated_Abs_Circle_Excercise from '../assets/latihan/Seated_Abs_Circle_Excercise.gif'
import Seated_abs_circles from '../assets/latihan/Seated_abs_circles.gif'
import Shoulder_Stretch_Excercise from '../assets/latihan/Shoulder_Stretch_Excercise.gif'
import single_leg_hip_rotation_exercise from '../assets/latihan/single_leg_hip_rotation_exercise.gif'
import Split_Jump_Exercise from '../assets/latihan/Split_Jump_Exercise.gif'
import Squat_Kick_Animation from '../assets/latihan/Squat_Kick_Animation.gif'
import Staggered_push_ups_excercises from '../assets/latihan/Staggered_push_ups_excercises.gif';
import Step_Up_On_Chair_Excercise from '../assets/latihan/Step_Up_On_Chair_Excercise.gif';
import T_Plank_Animation from '../assets/latihan/T_Plank_Animation.gif';
import T_Plank_Exercise_for_Home from '../assets/latihan/T_Plank_Exercise_for_Home.gif';
import Wide_arm_push_up_excercise from '../assets/latihan/Wide_arm_push_up_excercise.gif';
export {Burpee_and_Jump_Exercise,Jumping_Jack_Excercise,Cobras_exercises,Frog_press_excercise,Inchworm_workout_excercise,Jumping_squats_excercise,Lunge_Excercise,Military_Push_Ups_Exercise,Punches_Animation,Reverse_Crunches_Excercise,Seated_Abs_Circle_Excercise,Seated_abs_circles,Shoulder_Stretch_Excercise,single_leg_hip_rotation_exercise,Split_Jump_Exercise,Squat_Kick_Animation,Staggered_push_ups_excercises,Step_Up_On_Chair_Excercise,T_Plank_Animation,T_Plank_Exercise_for_Home,Wide_arm_push_up_excercise};